name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Pod Details App to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      - name: Build the Docker image
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wpniederer/return-pod-details-app
          path: src/
          tags: latest
